version: "3.8"
services:
    strapi:
        image: strapi/strapi
        volumes: 
            - ./strapi/app/:/srv/app
        ports:
            - 1337:1337
    front-end:
        ports:
            - 5001:8080
        build: front-end
        volumes:
            - ./front-end/src/:/code/src # connect the source code to the container for live-reloads during development
        entrypoint: [ "npm", "run", "dev-server" ]
        depends_on:
            - strapi
        links:
            - strapi